stages:
  - build
  - dockerize
  - deploy

variables:
  FLUTTER_VERSION: "stable"
  DOCKER_IMAGE: registry.gitlab.com/<YOUR_USERNAME>/<YOUR_PROJECT_NAME>:latest

# Build Flutter Web
build_flutter_web:
  stage: build
  image: cirrusci/flutter:$FLUTTER_VERSION
  script:
    - flutter pub get
    - flutter build web
  artifacts:
    paths:
      - build/web
    expire_in: 1 hour

# Build Docker image
docker_build:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main
  dependencies:
    - build_flutter_web

# Optional: Deploy step (if you have a server or runner to deploy)
deploy:
  stage: deploy
  script:
    - echo "Implement deployment step here (e.g., SSH to server, run docker pull & restart)"
  only:
    - main
  when: manual
