image: cirrusci/flutter:stable

stages:
  - build
  - deploy

before_script:
  - flutter pub get

build_apk:
  stage: build
  script:
    - echo "Building APK..."
    - chmod +x build.sh   # Cấp quyền chạy file nếu cần
    - ./build.sh          # Chạy script
    - flutter build apk --release
    - echo "APK built successfully."
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
